version: '3.1'

services:
  db:
    image: mysql
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080