version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT  
    volumes:
      # Mysql
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysqldb
    container_name: nodejs_server
    build: ./
    volumes:
      - ./server/:/app
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
    ports: 
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db: